unstable_features = true
newline_style = "Unix"

use_small_heuristics = "Off"
max_width = 180

group_imports = "StdExternalCrate"
merge_imports = true
imports_layout = "Horizontal"
imports_granularity = "Item"
