[package]
name = "skraid"
version = "0.1.5"
edition = "2018"
license = "MIT"

[dependencies]
serenity = "0.10"

[dependencies.rusqlite]
version = "0.25"
features = ["bundled"]

[dependencies.tokio]
version = "1.10"
features = ["macros", "rt-multi-thread"]